instructions:
  - "Instale as extensões recomendadas: PHP Intelephense, Prettier, Live Server, Tailwind CSS, Copilot, Copilot Chat, Auto Rename Tag, Path Intellisense, HTML/CSS Class Completion, Remote SSH, PowerShell."
  - "Ative o Copilot para todas as linguagens relevantes, exceto YAML, plaintext e markdown."
  - "Configure o Copilot: temperature 0.1, top_p 1, indentationMode conforme linguagem."
  - "Configure o PHP corretamente e desative sugestões básicas para evitar conflitos."
  - "Implemente tasks para iniciar o servidor local, abrir no navegador, validar HTML e otimizar imagens."
  - "Para chat por voz, instale e configure a extensão 'VS Code Speech - da Microsoft'."
  - "Use sempre os links oficiais para downloads e releases do Joomla. Para baixar e extrair, informe a versão e use:"
  - "wget -O Joomla_<versao>.zip https://github.com/joomla/joomla-cms/releases/download/<versao>/Joomla_<versao>-Stable-Full_Package.zip && 7z x Joomla_<versao>-Stable-Full_Package.zip -o. -aos && rm -rf installation"
  - "Exemplo (5.3.3):"
  - "wget -O Joomla_5.3.3-Stable-Full_Package.zip https://github.com/joomla/joomla-cms/releases/download/5.3.3/Joomla_5.3.3-Stable-Full_Package.zip && 7z x Joomla_5.3.3-Stable-Full_Package.zip -o. -aos && rm -rf installation"
  - "Siga os passos recomendados para instalar/atualizar o Joomla, evitando sobrescrever arquivos e removendo a pasta installation."
  - "Para backup do banco Joomla, use mysqldump com --default-character-set=utf8, --routines, --triggers, --single-transaction."
  - "Antes do backup, pergunte ao usuário quais opções incluir. Opções principais:"
  - "--add-drop-table: adiciona DROP TABLE antes de CREATE TABLE."
  - "--insert-ignore: usa INSERT IGNORE para evitar duplicidade."
  - "--replace: usa REPLACE em vez de INSERT."
  - "--create-options: inclui opções de criação de tabela."
  - "--no-create-info: não inclui CREATE TABLE."
  - "--no-data: exporta só estrutura."
  - "--if-not-exists: customizar no SQL."
  - "--update: customizar no SQL."
  - "Explique o impacto de cada opção, valide o backup e recomende armazenar em local seguro."
  - "Exemplo recomendado:"
  - "mysqldump --default-character-set=utf8 --routines --triggers --single-transaction --add-drop-table --insert-ignore -u <usuario> -p <banco> > tmp/backups/backup.sql"
  - "Prefira salvar o backup em tmp/backups. Use o formato projeto_banco_data-e-hora, ex: tmp/backups/radiofacialfrutal_radiofacialfrutal_2025-09-20_10-35.sql."
  - "Centralize instruções detalhadas em .vscode/definicoes_agente_ia.md para consulta do time."
  - "Valide e revise todo código sugerido antes de aplicar em produção."
instructions_en:
  - "Install recommended extensions: PHP Intelephense, Prettier, Live Server, Tailwind CSS, Copilot, Copilot Chat, Auto Rename Tag, Path Intellisense, HTML/CSS Class Completion, Remote SSH, PowerShell."
  - "Enable Copilot for all relevant languages except YAML, plaintext, and markdown."
  - "Configure Copilot: temperature 0.1, top_p 1, indentationMode according to language."
  - "Set up PHP correctly and disable basic suggestions to avoid conflicts."
  - "Implement tasks to start the local server, open in browser, validate HTML, and optimize images."
  - "For voice chat, install and configure the 'VS Code Speech - by Microsoft' extension."
  - "Always use official links for Joomla downloads and releases. To download and extract, specify the version and use:"
  - "wget -O Joomla_<version>.zip https://github.com/joomla/joomla-cms/releases/download/<version>/Joomla_<version>-Stable-Full_Package.zip && 7z x Joomla_<version>-Stable-Full_Package.zip -o. -aos && rm -rf installation"
  - "Example (5.3.3):"
  - "wget -O Joomla_5.3.3-Stable-Full_Package.zip https://github.com/joomla/joomla-cms/releases/download/5.3.3/Joomla_5.3.3-Stable-Full_Package.zip && 7z x Joomla_5.3.3-Stable-Full_Package.zip -o. -aos && rm -rf installation"
  - "Follow recommended steps to install/update Joomla, avoiding overwriting files and removing the installation folder."
  - "For Joomla database backup, use mysqldump with --default-character-set=utf8, --routines, --triggers, --single-transaction."
  - "Before backup, ask the user which options to include. Main options:"
  - "--add-drop-table: adds DROP TABLE before CREATE TABLE."
  - "--insert-ignore: uses INSERT IGNORE to avoid duplicates."
  - "--replace: uses REPLACE instead of INSERT."
  - "--create-options: includes table creation options."
  - "--no-create-info: does not include CREATE TABLE."
  - "--no-data: exports only structure."
  - "--if-not-exists: customize in SQL."
  - "--update: customize in SQL."
  - "Explain the impact of each option, validate the backup, and recommend storing in a safe location."
  - "Recommended example:"
  - "mysqldump --default-character-set=utf8 --routines --triggers --single-transaction --add-drop-table --insert-ignore -u <user> -p <database> > tmp/backups/backup.sql"
  - "Prefer saving the backup in tmp/backups. Use the format project_database_date-time, e.g.: tmp/backups/project_database_2025-09-20_10-35.sql."
  - "Centralize detailed instructions in .vscode/definicoes_agente_ia.md for team reference."
  - "Validate and review all suggested code before applying to production."
